export default {
  name: 'destination',
  title: 'Destination',
  type: 'document',
  fields: [
    { name: 'name', title: 'Name', type: 'string', validation: Rule => Rule.required() },
    { name: 'location', title: 'Location', type: 'string', description: 'The location or region of the destination' },
    { name: 'image', title: 'Image', type: 'image', options: { hotspot: true }, validation: Rule => Rule.required() },
    { name: 'tagline', title: 'Tagline', type: 'string' },
    { name: 'images', title: 'Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] },
    { name: 'videos', title: 'Videos', type: 'array', of: [{ type: 'url' }] },
    { name: 'description', title: 'Description', type: 'text' },
    { name: 'duration', title: 'Duration', type: 'string' },
    { name: 'difficulty', title: 'Difficulty', type: 'string', options: { list: [ { title: 'Easy', value: 'Easy' }, { title: 'Moderate', value: 'Moderate' }, { title: 'Challenging', value: 'Challenging' } ] } },
    { name: 'ageAllowed', title: 'Age Allowed', type: 'string' },
    { name: 'maxGroupSize', title: 'Max Group Size', type: 'number' },
    { name: 'rating', title: 'Rating', type: 'number' },
    { name: 'reviews', title: 'Reviews', type: 'number' },
    { name: 'about', title: 'About', type: 'text' },
    { name: 'highlights', title: 'Highlights', type: 'array', of: [{ type: 'string' }] },
    { name: 'joinUsFrom', title: 'Join Us From', type: 'array', of: [{ type: 'object', fields: [ { name: 'place', title: 'Place', type: 'string' }, { name: 'price', title: 'Price', type: 'string' }, { name: 'duration', title: 'Duration', type: 'string' }, { name: 'transport', title: 'Transport', type: 'string' } ] }] },
    { name: 'availableDates', title: 'Available Dates', type: 'array', of: [{ type: 'string' }] },
    { name: 'schedule', title: 'Schedule', type: 'array', of: [{ type: 'object', fields: [ { name: 'day', title: 'Day', type: 'number' }, { name: 'heading', title: 'Heading', type: 'string' }, { name: 'description', title: 'Description', type: 'text' }, { name: 'activities', title: 'Activities', type: 'array', of: [{ type: 'string' }] }, { name: 'images', title: 'Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] }, { name: 'meals', title: 'Meals', type: 'array', of: [{ type: 'string' }] } ] }] },
    { name: 'inclusions', title: 'Inclusions', type: 'array', of: [{ type: 'string' }] },
    { name: 'exclusions', title: 'Exclusions', type: 'array', of: [{ type: 'string' }] },
    { name: 'thingsToCarry', title: 'Things To Carry', type: 'array', of: [{ type: 'string' }] },
    { name: 'accommodation', title: 'Accommodation', type: 'object', fields: [ { name: 'type', title: 'Type', type: 'string' }, { name: 'facilities', title: 'Facilities', type: 'array', of: [{ type: 'string' }] }, { name: 'roomType', title: 'Room Type', type: 'string' } ] },
    { name: 'transport', title: 'Transport', type: 'object', fields: [ { name: 'type', title: 'Type', type: 'string' }, { name: 'pickup', title: 'Pickup', type: 'string' }, { name: 'departure', title: 'Departure', type: 'string' }, { name: 'return', title: 'Return', type: 'string' } ] },
    { name: 'cancellation', title: 'Cancellation', type: 'object', fields: [ { name: 'before7days', title: 'Before 7 Days', type: 'string' }, { name: 'before3days', title: 'Before 3 Days', type: 'string' }, { name: 'before1day', title: 'Before 1 Day', type: 'string' }, { name: 'sameDay', title: 'Same Day', type: 'string' } ] },
    { name: 'brochure', title: 'Brochure', type: 'file' },
    { name: 'faq', title: 'FAQ', type: 'array', of: [{ type: 'object', fields: [ { name: 'question', title: 'Question', type: 'string' }, { name: 'answer', title: 'Answer', type: 'text' } ] }] },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name', maxLength: 96 }, validation: Rule => Rule.required() },
  ],
}; 